name: Git Clone and Scan Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Clone external repository
      run: |
        git clone https://github.com/jai3747/test.git
        cd test  # Change directory to the cloned repo if necessary

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep --config=auto . --json > semgrep-results.json  # Save results in the current directory

    - name: Upload Semgrep results
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-results
        path: semgrep-results.json
